repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        'types': [ python ]
        require_serial: true
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        files: ^fastapi_sqlalchemy/
        entry: mypy --show-error-codes --no-warn-unused-ignores --follow-imports silent fastapi_sqlalchemy
        pass_filenames: false
        additional_dependencies:
          - 'pydantic'
          - 'sqlalchemy-stubs'
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: flake8
        description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
        entry: flake8
        language: python
        types: [ python ]
        require_serial: true
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ["-x", "tests"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-builtin-literals
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-yaml
